/**
 * S&P 500 constituents — the universe Discover's daily picks are sampled from.
 *
 * Snapshot of github.com/datasets/s-and-p-500-companies (data/constituents.csv)
 * as of 2026-09-21. No stock provider exposes index membership, so this list is
 * refreshed by hand when the index rebalances (see docs/design.md, Known Gaps).
 * Symbols are in Yahoo form: share-class dots become dashes (BRK.B → BRK-B).
 */
export interface UniverseEntry {
  symbol: string;
  name: string;
  /** GICS sector. */
  sector: string;
}

export const SP500: readonly UniverseEntry[] = [
  { symbol: 'MMM', name: '3M', sector: 'Industrials' },
  { symbol: 'AOS', name: 'A. O. Smith', sector: 'Industrials' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Health Care' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Health Care' },
  { symbol: 'ACN', name: 'Accenture', sector: 'Information Technology' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Information Technology' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Information Technology' },
  { symbol: 'AES', name: 'AES Corporation', sector: 'Utilities' },
  { symbol: 'AFL', name: 'Aflac', sector: 'Financials' },
  { symbol: 'A', name: 'Agilent Technologies', sector: 'Health Care' },
  { symbol: 'APD', name: 'Air Products', sector: 'Materials' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Consumer Discretionary' },
  { symbol: 'AKAM', name: 'Akamai Technologies', sector: 'Information Technology' },
  { symbol: 'ALB', name: 'Albemarle Corporation', sector: 'Materials' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities', sector: 'Real Estate' },
  { symbol: 'ALGN', name: 'Align Technology', sector: 'Health Care' },
  { symbol: 'ALLE', name: 'Allegion', sector: 'Industrials' },
  { symbol: 'LNT', name: 'Alliant Energy', sector: 'Utilities' },
  { symbol: 'ALL', name: 'Allstate', sector: 'Financials' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', sector: 'Communication Services' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', sector: 'Communication Services' },
  { symbol: 'MO', name: 'Altria', sector: 'Consumer Staples' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Consumer Discretionary' },
  { symbol: 'AMCR', name: 'Amcor', sector: 'Materials' },
  { symbol: 'AEE', name: 'Ameren', sector: 'Utilities' },
  { symbol: 'AEP', name: 'American Electric Power', sector: 'Utilities' },
  { symbol: 'AXP', name: 'American Express', sector: 'Financials' },
  { symbol: 'AIG', name: 'American International Group', sector: 'Financials' },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { symbol: 'AWK', name: 'American Water Works', sector: 'Utilities' },
  { symbol: 'AMP', name: 'Ameriprise Financial', sector: 'Financials' },
  { symbol: 'AME', name: 'Ametek', sector: 'Industrials' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Health Care' },
  { symbol: 'APH', name: 'Amphenol', sector: 'Information Technology' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Information Technology' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Financials' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy' },
  { symbol: 'APO', name: 'Apollo Global Management', sector: 'Financials' },
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Information Technology' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Information Technology' },
  { symbol: 'APP', name: 'AppLovin', sector: 'Communication Services' },
  { symbol: 'APTV', name: 'Aptiv', sector: 'Consumer Discretionary' },
  { symbol: 'ACGL', name: 'Arch Capital Group', sector: 'Financials' },
  { symbol: 'ADM', name: 'Archer Daniels Midland', sector: 'Consumer Staples' },
  { symbol: 'ARES', name: 'Ares Management', sector: 'Financials' },
  { symbol: 'ANET', name: 'Arista Networks', sector: 'Information Technology' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', sector: 'Financials' },
  { symbol: 'AIZ', name: 'Assurant', sector: 'Financials' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication Services' },
  { symbol: 'ATO', name: 'Atmos Energy', sector: 'Utilities' },
  { symbol: 'ADSK', name: 'Autodesk', sector: 'Information Technology' },
  { symbol: 'ADP', name: 'Automatic Data Processing', sector: 'Industrials' },
  { symbol: 'AZO', name: 'AutoZone', sector: 'Consumer Discretionary' },
  { symbol: 'AVY', name: 'Avery Dennison', sector: 'Materials' },
  { symbol: 'AXON', name: 'Axon Enterprise', sector: 'Industrials' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'BALL', name: 'Ball Corporation', sector: 'Materials' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Financials' },
  { symbol: 'BAX', name: 'Baxter International', sector: 'Health Care' },
  { symbol: 'BDX', name: 'Becton Dickinson', sector: 'Health Care' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', sector: 'Financials' },
  { symbol: 'BBY', name: 'Best Buy', sector: 'Consumer Discretionary' },
  { symbol: 'TECH', name: 'Bio-Techne', sector: 'Health Care' },
  { symbol: 'BIIB', name: 'Biogen', sector: 'Health Care' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Financials' },
  { symbol: 'BX', name: 'Blackstone Inc.', sector: 'Financials' },
  { symbol: 'XYZ', name: 'Block, Inc.', sector: 'Financials' },
  { symbol: 'BE', name: 'Bloom Energy', sector: 'Industrials' },
  { symbol: 'BNY', name: 'BNY Mellon', sector: 'Financials' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrials' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Discretionary' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Health Care' },
  { symbol: 'BMY', name: 'Bristol Myers Squibb', sector: 'Health Care' },
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Information Technology' },
  { symbol: 'BR', name: 'Broadridge Financial Solutions', sector: 'Industrials' },
  { symbol: 'BRO', name: 'Brown & Brown', sector: 'Financials' },
  { symbol: 'BF-B', name: 'Brown–Forman', sector: 'Consumer Staples' },
  { symbol: 'BG', name: 'Bunge Global', sector: 'Consumer Staples' },
  { symbol: 'BXP', name: 'BXP, Inc.', sector: 'Real Estate' },
  { symbol: 'CHRW', name: 'C.H. Robinson', sector: 'Industrials' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Information Technology' },
  { symbol: 'CPT', name: 'Camden Property Trust', sector: 'Real Estate' },
  { symbol: 'COF', name: 'Capital One', sector: 'Financials' },
  { symbol: 'CAH', name: 'Cardinal Health', sector: 'Health Care' },
  { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'CARR', name: 'Carrier Global', sector: 'Industrials' },
  { symbol: 'CVNA', name: 'Carvana', sector: 'Consumer Discretionary' },
  { symbol: 'CASY', name: "Casey's", sector: 'Consumer Staples' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials' },
  { symbol: 'CBOE', name: 'Cboe Global Markets', sector: 'Financials' },
  { symbol: 'CBRE', name: 'CBRE Group', sector: 'Real Estate' },
  { symbol: 'CDW', name: 'CDW Corporation', sector: 'Information Technology' },
  { symbol: 'COR', name: 'Cencora', sector: 'Health Care' },
  { symbol: 'CNC', name: 'Centene Corporation', sector: 'Health Care' },
  { symbol: 'CNP', name: 'CenterPoint Energy', sector: 'Utilities' },
  { symbol: 'CF', name: 'CF Industries', sector: 'Materials' },
  { symbol: 'CRL', name: 'Charles River Laboratories', sector: 'Health Care' },
  { symbol: 'SCHW', name: 'Charles Schwab Corporation', sector: 'Financials' },
  { symbol: 'CHTR', name: 'Charter Communications', sector: 'Communication Services' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer Discretionary' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Financials' },
  { symbol: 'CHD', name: 'Church & Dwight', sector: 'Consumer Staples' },
  { symbol: 'CIEN', name: 'Ciena', sector: 'Information Technology' },
  { symbol: 'CI', name: 'Cigna', sector: 'Health Care' },
  { symbol: 'CINF', name: 'Cincinnati Financial', sector: 'Financials' },
  { symbol: 'CTAS', name: 'Cintas', sector: 'Industrials' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Information Technology' },
  { symbol: 'C', name: 'Citigroup', sector: 'Financials' },
  { symbol: 'CFG', name: 'Citizens Financial Group', sector: 'Financials' },
  { symbol: 'CLX', name: 'Clorox', sector: 'Consumer Staples' },
  { symbol: 'CME', name: 'CME Group', sector: 'Financials' },
  { symbol: 'CMS', name: 'CMS Energy', sector: 'Utilities' },
  { symbol: 'KO', name: 'Coca-Cola Company (The)', sector: 'Consumer Staples' },
  { symbol: 'CTSH', name: 'Cognizant', sector: 'Information Technology' },
  { symbol: 'COHR', name: 'Coherent Corp.', sector: 'Information Technology' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Financials' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Staples' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Communication Services' },
  { symbol: 'FIX', name: 'Comfort Systems USA', sector: 'Industrials' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
  { symbol: 'STZ', name: 'Constellation Brands', sector: 'Consumer Staples' },
  { symbol: 'CEG', name: 'Constellation Energy', sector: 'Utilities' },
  { symbol: 'COO', name: 'Cooper Companies (The)', sector: 'Health Care' },
  { symbol: 'CPRT', name: 'Copart', sector: 'Industrials' },
  { symbol: 'GLW', name: 'Corning Inc.', sector: 'Information Technology' },
  { symbol: 'CPAY', name: 'Corpay', sector: 'Financials' },
  { symbol: 'CTVA', name: 'Corteva', sector: 'Materials' },
  { symbol: 'CSGP', name: 'CoStar Group', sector: 'Real Estate' },
  { symbol: 'COST', name: 'Costco', sector: 'Consumer Staples' },
  { symbol: 'CRH', name: 'CRH plc', sector: 'Materials' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Information Technology' },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { symbol: 'CSX', name: 'CSX Corporation', sector: 'Industrials' },
  { symbol: 'CMI', name: 'Cummins', sector: 'Industrials' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Health Care' },
  { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Health Care' },
  { symbol: 'DRI', name: 'Darden Restaurants', sector: 'Consumer Discretionary' },
  { symbol: 'DDOG', name: 'Datadog', sector: 'Information Technology' },
  { symbol: 'DVA', name: 'DaVita', sector: 'Health Care' },
  { symbol: 'DECK', name: 'Deckers Brands', sector: 'Consumer Discretionary' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrials' },
  { symbol: 'DELL', name: 'Dell Technologies', sector: 'Information Technology' },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrials' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'DXCM', name: 'Dexcom', sector: 'Health Care' },
  { symbol: 'FANG', name: 'Diamondback Energy', sector: 'Energy' },
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { symbol: 'DG', name: 'Dollar General', sector: 'Consumer Staples' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer Staples' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { symbol: 'DPZ', name: "Domino's", sector: 'Consumer Discretionary' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Consumer Discretionary' },
  { symbol: 'DOV', name: 'Dover Corporation', sector: 'Industrials' },
  { symbol: 'DOW', name: 'Dow Inc.', sector: 'Materials' },
  { symbol: 'DHI', name: 'D. R. Horton', sector: 'Consumer Discretionary' },
  { symbol: 'DTE', name: 'DTE Energy', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'DD', name: 'DuPont', sector: 'Industrials' },
  { symbol: 'ETN', name: 'Eaton Corporation', sector: 'Industrials' },
  { symbol: 'EBAY', name: 'eBay Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'ECHO', name: 'EchoStar', sector: 'Communication Services' },
  { symbol: 'ECL', name: 'Ecolab', sector: 'Materials' },
  { symbol: 'EIX', name: 'Edison International', sector: 'Utilities' },
  { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Health Care' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Health Care' },
  { symbol: 'EME', name: 'Emcor', sector: 'Industrials' },
  { symbol: 'EMR', name: 'Emerson Electric', sector: 'Industrials' },
  { symbol: 'ETR', name: 'Entergy', sector: 'Utilities' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy' },
  { symbol: 'EFX', name: 'Equifax', sector: 'Industrials' },
  { symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate' },
  { symbol: 'ERIE', name: 'Erie Indemnity', sector: 'Financials' },
  { symbol: 'ESS', name: 'Essex Property Trust', sector: 'Real Estate' },
  { symbol: 'EL', name: 'Estée Lauder Companies (The)', sector: 'Consumer Staples' },
  { symbol: 'EG', name: 'Everest Group', sector: 'Financials' },
  { symbol: 'EVRG', name: 'Evergy', sector: 'Utilities' },
  { symbol: 'P', name: 'Everpure', sector: 'Information Technology' },
  { symbol: 'ES', name: 'Eversource Energy', sector: 'Utilities' },
  { symbol: 'EXC', name: 'Exelon', sector: 'Utilities' },
  { symbol: 'EXE', name: 'Expand Energy', sector: 'Energy' },
  { symbol: 'EXPE', name: 'Expedia Group', sector: 'Consumer Discretionary' },
  { symbol: 'EXPD', name: 'Expeditors International', sector: 'Industrials' },
  { symbol: 'EXR', name: 'Extra Space Storage', sector: 'Real Estate' },
  { symbol: 'XOM', name: 'ExxonMobil', sector: 'Energy' },
  { symbol: 'FFIV', name: 'F5, Inc.', sector: 'Information Technology' },
  { symbol: 'FDS', name: 'FactSet', sector: 'Financials' },
  { symbol: 'FICO', name: 'Fair Isaac', sector: 'Information Technology' },
  { symbol: 'FAST', name: 'Fastenal', sector: 'Industrials' },
  { symbol: 'FRT', name: 'Federal Realty Investment Trust', sector: 'Real Estate' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrials' },
  { symbol: 'FDXF', name: 'FedEx Freight', sector: 'Industrials' },
  { symbol: 'FERG', name: 'Ferguson Enterprises', sector: 'Industrials' },
  { symbol: 'FIS', name: 'Fidelity National Information Services', sector: 'Financials' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Financials' },
  { symbol: 'FSLR', name: 'First Solar', sector: 'Information Technology' },
  { symbol: 'FE', name: 'FirstEnergy', sector: 'Utilities' },
  { symbol: 'FISV', name: 'Fiserv', sector: 'Financials' },
  { symbol: 'FLEX', name: 'Flex Ltd.', sector: 'Information Technology' },
  { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumer Discretionary' },
  { symbol: 'FTNT', name: 'Fortinet', sector: 'Information Technology' },
  { symbol: 'FTV', name: 'Fortive', sector: 'Industrials' },
  { symbol: 'FOXA', name: 'Fox Corporation (Class A)', sector: 'Communication Services' },
  { symbol: 'FOX', name: 'Fox Corporation (Class B)', sector: 'Communication Services' },
  { symbol: 'BEN', name: 'Franklin Resources', sector: 'Financials' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials' },
  { symbol: 'GRMN', name: 'Garmin', sector: 'Consumer Discretionary' },
  { symbol: 'IT', name: 'Gartner', sector: 'Information Technology' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrials' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Health Care' },
  { symbol: 'GEV', name: 'GE Vernova', sector: 'Industrials' },
  { symbol: 'GEN', name: 'Gen Digital', sector: 'Information Technology' },
  { symbol: 'GNRC', name: 'Generac', sector: 'Industrials' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Industrials' },
  { symbol: 'GIS', name: 'General Mills', sector: 'Consumer Staples' },
  { symbol: 'GM', name: 'General Motors', sector: 'Consumer Discretionary' },
  { symbol: 'GPC', name: 'Genuine Parts Company', sector: 'Consumer Discretionary' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Health Care' },
  { symbol: 'GPN', name: 'Global Payments', sector: 'Financials' },
  { symbol: 'GL', name: 'Globe Life', sector: 'Financials' },
  { symbol: 'GDDY', name: 'GoDaddy', sector: 'Information Technology' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financials' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { symbol: 'HIG', name: 'Hartford (The)', sector: 'Financials' },
  { symbol: 'HAS', name: 'Hasbro', sector: 'Consumer Discretionary' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Health Care' },
  { symbol: 'DOC', name: 'Healthpeak Properties', sector: 'Real Estate' },
  { symbol: 'HSIC', name: 'Henry Schein', sector: 'Health Care' },
  { symbol: 'HSY', name: 'Hershey Company (The)', sector: 'Consumer Staples' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Information Technology' },
  { symbol: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer Discretionary' },
  { symbol: 'HD', name: 'Home Depot (The)', sector: 'Consumer Discretionary' },
  { symbol: 'HONA', name: 'Honeywell Aerospace', sector: 'Industrials' },
  { symbol: 'HON', name: 'Honeywell Technologies', sector: 'Industrials' },
  { symbol: 'HRL', name: 'Hormel Foods', sector: 'Consumer Staples' },
  { symbol: 'HST', name: 'Host Hotels & Resorts', sector: 'Real Estate' },
  { symbol: 'HWM', name: 'Howmet Aerospace', sector: 'Industrials' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Information Technology' },
  { symbol: 'HUBB', name: 'Hubbell Incorporated', sector: 'Industrials' },
  { symbol: 'HUM', name: 'Humana', sector: 'Health Care' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Financials' },
  { symbol: 'HII', name: 'Huntington Ingalls Industries', sector: 'Industrials' },
  { symbol: 'IBM', name: 'IBM', sector: 'Information Technology' },
  { symbol: 'IEX', name: 'IDEX Corporation', sector: 'Industrials' },
  { symbol: 'IDXX', name: 'Idexx Laboratories', sector: 'Health Care' },
  { symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrials' },
  { symbol: 'ILMN', name: 'Illumina, Inc.', sector: 'Health Care' },
  { symbol: 'INCY', name: 'Incyte', sector: 'Health Care' },
  { symbol: 'IR', name: 'Ingersoll Rand', sector: 'Industrials' },
  { symbol: 'PODD', name: 'Insulet Corporation', sector: 'Health Care' },
  { symbol: 'INTC', name: 'Intel', sector: 'Information Technology' },
  { symbol: 'IBKR', name: 'Interactive Brokers', sector: 'Financials' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financials' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances', sector: 'Materials' },
  { symbol: 'IP', name: 'International Paper', sector: 'Materials' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Information Technology' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Health Care' },
  { symbol: 'IVZ', name: 'Invesco', sector: 'Financials' },
  { symbol: 'INVH', name: 'Invitation Homes', sector: 'Real Estate' },
  { symbol: 'IQV', name: 'IQVIA', sector: 'Health Care' },
  { symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },
  { symbol: 'JBHT', name: 'J.B. Hunt', sector: 'Industrials' },
  { symbol: 'JBL', name: 'Jabil', sector: 'Information Technology' },
  { symbol: 'JKHY', name: 'Jack Henry & Associates', sector: 'Financials' },
  { symbol: 'J', name: 'Jacobs Solutions', sector: 'Industrials' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care' },
  { symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrials' },
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Financials' },
  { symbol: 'KVUE', name: 'Kenvue', sector: 'Consumer Staples' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', sector: 'Consumer Staples' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Financials' },
  { symbol: 'KEYS', name: 'Keysight Technologies', sector: 'Information Technology' },
  { symbol: 'KMB', name: 'Kimberly-Clark', sector: 'Consumer Staples' },
  { symbol: 'KIM', name: 'Kimco Realty', sector: 'Real Estate' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'KKR', name: 'KKR & Co.', sector: 'Financials' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Information Technology' },
  { symbol: 'KHC', name: 'Kraft Heinz', sector: 'Consumer Staples' },
  { symbol: 'KR', name: 'Kroger', sector: 'Consumer Staples' },
  { symbol: 'LHX', name: 'L3Harris', sector: 'Industrials' },
  { symbol: 'LH', name: 'Labcorp', sector: 'Health Care' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Information Technology' },
  { symbol: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer Discretionary' },
  { symbol: 'LDOS', name: 'Leidos', sector: 'Industrials' },
  { symbol: 'LEN', name: 'Lennar', sector: 'Consumer Discretionary' },
  { symbol: 'LII', name: 'Lennox International', sector: 'Industrials' },
  { symbol: 'LLY', name: 'Lilly (Eli)', sector: 'Health Care' },
  { symbol: 'LIN', name: 'Linde plc', sector: 'Materials' },
  { symbol: 'LYV', name: 'Live Nation Entertainment', sector: 'Communication Services' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials' },
  { symbol: 'L', name: 'Loews Corporation', sector: 'Financials' },
  { symbol: 'LOW', name: "Lowe's", sector: 'Consumer Discretionary' },
  { symbol: 'LULU', name: 'Lululemon Athletica', sector: 'Consumer Discretionary' },
  { symbol: 'LITE', name: 'Lumentum', sector: 'Information Technology' },
  { symbol: 'LYB', name: 'LyondellBasell', sector: 'Materials' },
  { symbol: 'MTB', name: 'M&T Bank', sector: 'Financials' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { symbol: 'MAR', name: 'Marriott International', sector: 'Consumer Discretionary' },
  { symbol: 'MRSH', name: 'Marsh McLennan', sector: 'Financials' },
  { symbol: 'MLM', name: 'Martin Marietta Materials', sector: 'Materials' },
  { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Information Technology' },
  { symbol: 'MAS', name: 'Masco', sector: 'Industrials' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Financials' },
  { symbol: 'MKC', name: 'McCormick & Company', sector: 'Consumer Staples' },
  { symbol: 'MCD', name: "McDonald's", sector: 'Consumer Discretionary' },
  { symbol: 'MCK', name: 'McKesson Corporation', sector: 'Health Care' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Health Care' },
  { symbol: 'MRK', name: 'Merck & Co.', sector: 'Health Care' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Communication Services' },
  { symbol: 'MET', name: 'MetLife', sector: 'Financials' },
  { symbol: 'MTD', name: 'Mettler Toledo', sector: 'Health Care' },
  { symbol: 'MGM', name: 'MGM Resorts', sector: 'Consumer Discretionary' },
  { symbol: 'MCHP', name: 'Microchip Technology', sector: 'Information Technology' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Information Technology' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Information Technology' },
  { symbol: 'MAA', name: 'Mid-America Apartment Communities', sector: 'Real Estate' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Health Care' },
  { symbol: 'MDLZ', name: 'Mondelez International', sector: 'Consumer Staples' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems', sector: 'Information Technology' },
  { symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer Staples' },
  { symbol: 'MCO', name: "Moody's Corporation", sector: 'Financials' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials' },
  { symbol: 'MOS', name: 'Mosaic Company (The)', sector: 'Materials' },
  { symbol: 'MSI', name: 'Motorola Solutions', sector: 'Information Technology' },
  { symbol: 'MSCI', name: 'MSCI', sector: 'Financials' },
  { symbol: 'NDAQ', name: 'Nasdaq, Inc.', sector: 'Financials' },
  { symbol: 'NTAP', name: 'NetApp', sector: 'Information Technology' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Communication Services' },
  { symbol: 'NEM', name: 'Newmont', sector: 'Materials' },
  { symbol: 'NWSA', name: 'News Corp (Class A)', sector: 'Communication Services' },
  { symbol: 'NWS', name: 'News Corp (Class B)', sector: 'Communication Services' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'NKE', name: 'Nike, Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NI', name: 'NiSource', sector: 'Utilities' },
  { symbol: 'NDSN', name: 'Nordson Corporation', sector: 'Industrials' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrials' },
  { symbol: 'NTRS', name: 'Northern Trust', sector: 'Financials' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrials' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings', sector: 'Consumer Discretionary' },
  { symbol: 'NRG', name: 'NRG Energy', sector: 'Utilities' },
  { symbol: 'NUE', name: 'Nucor', sector: 'Materials' },
  { symbol: 'NVDA', name: 'Nvidia', sector: 'Information Technology' },
  { symbol: 'NVR', name: 'NVR, Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Information Technology' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", sector: 'Consumer Discretionary' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'ODFL', name: 'Old Dominion', sector: 'Industrials' },
  { symbol: 'OMC', name: 'Omnicom Group', sector: 'Communication Services' },
  { symbol: 'ON', name: 'ON Semiconductor', sector: 'Information Technology' },
  { symbol: 'OKE', name: 'Oneok', sector: 'Energy' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Information Technology' },
  { symbol: 'OTIS', name: 'Otis Worldwide', sector: 'Industrials' },
  { symbol: 'PCAR', name: 'Paccar', sector: 'Industrials' },
  { symbol: 'PKG', name: 'Packaging Corporation of America', sector: 'Materials' },
  { symbol: 'PLTR', name: 'Palantir Technologies', sector: 'Information Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Information Technology' },
  { symbol: 'PSKY', name: 'Paramount Skydance Corporation', sector: 'Communication Services' },
  { symbol: 'PH', name: 'Parker Hannifin', sector: 'Industrials' },
  { symbol: 'PAYX', name: 'Paychex', sector: 'Industrials' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Financials' },
  { symbol: 'PNR', name: 'Pentair', sector: 'Industrials' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer Staples' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Health Care' },
  { symbol: 'PCG', name: 'PG&E Corporation', sector: 'Utilities' },
  { symbol: 'PM', name: 'Philip Morris International', sector: 'Consumer Staples' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'PNW', name: 'Pinnacle West Capital', sector: 'Utilities' },
  { symbol: 'PNC', name: 'PNC Financial Services', sector: 'Financials' },
  { symbol: 'PPG', name: 'PPG Industries', sector: 'Materials' },
  { symbol: 'PPL', name: 'PPL Corporation', sector: 'Utilities' },
  { symbol: 'PFG', name: 'Principal Financial Group', sector: 'Financials' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer Staples' },
  { symbol: 'PGR', name: 'Progressive Corporation', sector: 'Financials' },
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'PRU', name: 'Prudential Financial', sector: 'Financials' },
  { symbol: 'PEG', name: 'Public Service Enterprise Group', sector: 'Utilities' },
  { symbol: 'PTC', name: 'PTC Inc.', sector: 'Information Technology' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'PHM', name: 'PulteGroup', sector: 'Consumer Discretionary' },
  { symbol: 'PWR', name: 'Quanta Services', sector: 'Industrials' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Information Technology' },
  { symbol: 'DGX', name: 'Quest Diagnostics', sector: 'Health Care' },
  { symbol: 'Q', name: 'Qnity Electronics', sector: 'Information Technology' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'RJF', name: 'Raymond James Financial', sector: 'Financials' },
  { symbol: 'RDDT', name: 'Reddit', sector: 'Communication Services' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrials' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'REG', name: 'Regency Centers', sector: 'Real Estate' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Health Care' },
  { symbol: 'RF', name: 'Regions Financial Corporation', sector: 'Financials' },
  { symbol: 'RSG', name: 'Republic Services', sector: 'Industrials' },
  { symbol: 'RMD', name: 'ResMed|', sector: 'Health Care' },
  { symbol: 'RVTY', name: 'Revvity', sector: 'Health Care' },
  { symbol: 'HOOD', name: 'Robinhood Markets', sector: 'Financials' },
  { symbol: 'ROK', name: 'Rockwell Automation', sector: 'Industrials' },
  { symbol: 'ROL', name: 'Rollins, Inc.', sector: 'Industrials' },
  { symbol: 'ROP', name: 'Roper Technologies', sector: 'Information Technology' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer Discretionary' },
  { symbol: 'RCL', name: 'Royal Caribbean Group', sector: 'Consumer Discretionary' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Financials' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Information Technology' },
  { symbol: 'SNDK', name: 'Sandisk', sector: 'Information Technology' },
  { symbol: 'SBAC', name: 'SBA Communications', sector: 'Real Estate' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'STX', name: 'Seagate Technology', sector: 'Information Technology' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Information Technology' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials' },
  { symbol: 'SPG', name: 'Simon Property Group', sector: 'Real Estate' },
  { symbol: 'SWKS', name: 'Skyworks Solutions', sector: 'Information Technology' },
  { symbol: 'SJM', name: 'J.M. Smucker Company (The)', sector: 'Consumer Staples' },
  { symbol: 'SW', name: 'Smurfit Westrock', sector: 'Materials' },
  { symbol: 'SNA', name: 'Snap-on', sector: 'Industrials' },
  { symbol: 'SOLV', name: 'Solventum', sector: 'Health Care' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
  { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrials' },
  { symbol: 'SWK', name: 'Stanley Black & Decker', sector: 'Industrials' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Discretionary' },
  { symbol: 'STT', name: 'State Street Corporation', sector: 'Financials' },
  { symbol: 'STLD', name: 'Steel Dynamics', sector: 'Materials' },
  { symbol: 'STE', name: 'Steris', sector: 'Health Care' },
  { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Health Care' },
  { symbol: 'SMCI', name: 'Supermicro', sector: 'Information Technology' },
  { symbol: 'SYF', name: 'Synchrony Financial', sector: 'Financials' },
  { symbol: 'SNPS', name: 'Synopsys', sector: 'Information Technology' },
  { symbol: 'SYY', name: 'Sysco', sector: 'Consumer Staples' },
  { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Communication Services' },
  { symbol: 'TROW', name: 'T. Rowe Price', sector: 'Financials' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication Services' },
  { symbol: 'TPR', name: 'Tapestry, Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'TRGP', name: 'Targa Resources', sector: 'Energy' },
  { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer Staples' },
  { symbol: 'TEL', name: 'TE Connectivity', sector: 'Information Technology' },
  { symbol: 'TDY', name: 'Teledyne Technologies', sector: 'Information Technology' },
  { symbol: 'TER', name: 'Teradyne', sector: 'Information Technology' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Information Technology' },
  { symbol: 'TPL', name: 'Texas Pacific Land Corporation', sector: 'Energy' },
  { symbol: 'TXT', name: 'Textron', sector: 'Industrials' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Health Care' },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer Discretionary' },
  { symbol: 'TKO', name: 'TKO Group Holdings', sector: 'Communication Services' },
  { symbol: 'TSCO', name: 'Tractor Supply', sector: 'Consumer Discretionary' },
  { symbol: 'TT', name: 'Trane Technologies', sector: 'Industrials' },
  { symbol: 'TDG', name: 'TransDigm Group', sector: 'Industrials' },
  { symbol: 'TRV', name: 'Travelers Companies (The)', sector: 'Financials' },
  { symbol: 'TRMB', name: 'Trimble Inc.', sector: 'Information Technology' },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Financials' },
  { symbol: 'TYL', name: 'Tyler Technologies', sector: 'Information Technology' },
  { symbol: 'TSN', name: 'Tyson Foods', sector: 'Consumer Staples' },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financials' },
  { symbol: 'UBER', name: 'Uber', sector: 'Industrials' },
  { symbol: 'UDR', name: 'UDR, Inc.', sector: 'Real Estate' },
  { symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Consumer Discretionary' },
  { symbol: 'UNP', name: 'Union Pacific Corporation', sector: 'Industrials' },
  { symbol: 'UAL', name: 'United Airlines Holdings', sector: 'Industrials' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrials' },
  { symbol: 'URI', name: 'United Rentals', sector: 'Industrials' },
  { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Health Care' },
  { symbol: 'UHS', name: 'Universal Health Services', sector: 'Health Care' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { symbol: 'VEEV', name: 'Veeva Systems', sector: 'Health Care' },
  { symbol: 'VTR', name: 'Ventas', sector: 'Real Estate' },
  { symbol: 'VLTO', name: 'Veralto', sector: 'Industrials' },
  { symbol: 'VRSN', name: 'Verisign', sector: 'Information Technology' },
  { symbol: 'VRSK', name: 'Verisk Analytics', sector: 'Industrials' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication Services' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Health Care' },
  { symbol: 'VRT', name: 'Vertiv', sector: 'Industrials' },
  { symbol: 'VTRS', name: 'Viatris', sector: 'Health Care' },
  { symbol: 'VICI', name: 'Vici Properties', sector: 'Real Estate' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financials' },
  { symbol: 'VST', name: 'Vistra Corp.', sector: 'Utilities' },
  { symbol: 'VMRK', name: 'Vivmark Residential', sector: 'Real Estate' },
  { symbol: 'VMC', name: 'Vulcan Materials Company', sector: 'Materials' },
  { symbol: 'WRB', name: 'W. R. Berkley Corporation', sector: 'Financials' },
  { symbol: 'GWW', name: 'W. W. Grainger', sector: 'Industrials' },
  { symbol: 'WAB', name: 'Wabtec', sector: 'Industrials' },
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer Staples' },
  { symbol: 'DIS', name: 'Walt Disney Company (The)', sector: 'Communication Services' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication Services' },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrials' },
  { symbol: 'WAT', name: 'Waters Corporation', sector: 'Health Care' },
  { symbol: 'WEC', name: 'WEC Energy Group', sector: 'Utilities' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Financials' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'WST', name: 'West Pharmaceutical Services', sector: 'Health Care' },
  { symbol: 'WDC', name: 'Western Digital', sector: 'Information Technology' },
  { symbol: 'WY', name: 'Weyerhaeuser', sector: 'Real Estate' },
  { symbol: 'WSM', name: 'Williams-Sonoma, Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'WMB', name: 'Williams Companies', sector: 'Energy' },
  { symbol: 'WTW', name: 'Willis Towers Watson', sector: 'Financials' },
  { symbol: 'WDAY', name: 'Workday, Inc.', sector: 'Information Technology' },
  { symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer Discretionary' },
  { symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { symbol: 'XYL', name: 'Xylem Inc.', sector: 'Industrials' },
  { symbol: 'YUM', name: 'Yum! Brands', sector: 'Consumer Discretionary' },
  { symbol: 'ZBRA', name: 'Zebra Technologies', sector: 'Information Technology' },
  { symbol: 'ZBH', name: 'Zimmer Biomet', sector: 'Health Care' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Health Care' },
];
