CREATE TABLE `game_player_stats` (
	`game_player_id` text PRIMARY KEY NOT NULL,
	`peak_portfolio_value` real,
	`peak_portfolio_at` text,
	`trough_portfolio_value` real,
	`trough_portfolio_at` text,
	`best_rank` integer,
	`worst_rank` integer,
	`last_rank` integer,
	`days_at_rank_one` integer DEFAULT 0 NOT NULL,
	`consecutive_days_at_rank_one` integer DEFAULT 0 NOT NULL,
	`days_in_top_three` integer DEFAULT 0 NOT NULL,
	`consecutive_days_at_or_above_median` integer DEFAULT 0 NOT NULL,
	`consecutive_days_in_last_place` integer DEFAULT 0 NOT NULL,
	`last_day_counted` text,
	`last_day_rank` integer,
	`total_trades` integer DEFAULT 0 NOT NULL,
	`buy_trades` integer DEFAULT 0 NOT NULL,
	`sell_trades` integer DEFAULT 0 NOT NULL,
	`distinct_symbols_traded_ever` integer DEFAULT 0 NOT NULL,
	`total_volume_traded` real DEFAULT 0 NOT NULL,
	`realized_pnl` real DEFAULT 0 NOT NULL,
	`winning_closed_positions` integer DEFAULT 0 NOT NULL,
	`losing_closed_positions` integer DEFAULT 0 NOT NULL,
	`consecutive_wins` integer DEFAULT 0 NOT NULL,
	`best_single_pnl` real,
	`worst_single_pnl` real,
	`best_single_pnl_pct` real,
	`worst_single_pnl_pct` real,
	`shortest_hold_ms` integer,
	`longest_hold_ms` integer,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`game_player_id`) REFERENCES `game_players`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
ALTER TABLE `portfolios` ADD `opened_at` text;